### PR TITLE
Adds use case documentation

### PR DESCRIPTION
**Pull request by bwalsh**
* Adds markdown and images harvested from https://docs.google.com/document/d/1xhjksU9CtTu0F297A1n05eMM2MxQ_--fYqVImAFns68/edit#

* Re-generates site

### CODE REVIEW

**Comment by bwalsh** [comment]
We need to re-generate after content in google doc finalized

**Comment by liberaliscomputing** [comment]
It seems that we can remove one-level sub-headers for 6 Use Cases and 3 Background. For example, in 6 Use Cases, there is 6.1 Use Cases unnecessarily. So, in the Google Doc, I added headers to each section and could you make changes to the markdown files according to these headers?

**Review by liberaliscomputing — APPROVED** [review]
Looks good to me!

**Review by allisonheath — APPROVED** [review]
Looks good for the first pass!

**Pull request merged**
